FROM oven/bun:1
WORKDIR /usr/src/app

ARG DATABASE_URL

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock
COPY ./packages.json ./packages.json
COPY ./turbo.json ./turbo.json
COPY ./apps/web ./apps/web

RUN bun install

RUN bun run db:generate

RUN DATABASE_URL=${DATABASE_URL} bun run build

EXPOSE 8080

CMD [ "bun", "run", "start:web" ]

